language: objective-c
osx_image: xcode8.3
rvm:
- 2.2
cache:
  directories:
    - /Users/travis/.rvm/
    - /Users/travis/Downloads/
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file:
    - ./Build/linux.zip
    - ./Build/mac.zip
    - ./Build/windows.zip
  skip_cleanup: true
  on:
    branch: master
